[project]
name = "RouterGym"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "pandas",
    "faiss-cpu",
    "sentence-transformers",
    "matplotlib",
    "pyyaml",
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
